### PR TITLE
Updated docs on Packet now Equinix Metal

### PR DESCRIPTION
**Pull request by bjerrecs**
Hello.

I have written some new docs for Equinix Metal as they have replaced Packet.
They still offer a great service and therefore it should not just be deleted.

Maybe the GNS3 team can come to an agreement on a discount like with Packet?

I'm willing to make changes and keep working on this until it meets some standard.

Maybe the https://docs.gns3.com/docs/contribute/contribute-to-gns3 needs to be updated?

### CODE REVIEW

**Comment by grossmj** [comment]
Hi,

Thanks a lot for your contribution, I will review soon.

> Maybe the GNS3 team can come to an agreement on a discount like with Packet?

We have the following coupon for our users: `GNS3METAL` which should give a $25 credit on Equinix metal.

**Comment by bjerrecs** [comment]
Super, will add to the docs

På lør., 3 dec., 2022 kl. 14:01, Jeremy Grossmann ***@***.***> skrev:

**Comment by bjerrecs** [comment]
Hi @grossmj 

I have added the offer line, please review when there is time

**Comment by grossmj** [comment]
Perfect, thanks for your help :)

**Pull request merged**
